version: "2"
services:
  contents:
    image: 13.112.188.210:5000/app/contents
    container_name: contents
    environment:
      SPRING_CLOUD_CONFIG_LABEL: scc
      INFO_CONFIG_HOSTNAME: 54.168.54.7
      INFO_EUREKA_HOSTNAME: 54.168.54.7
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "9120:9120"
    networks:
      - msa_blank
networks:
    msa_blank:
      external: true
